import { createTamagui } from "@tamagui/core";

// 기본 Tamagui 설정
export const config = createTamagui({
    themes: {
        light: {
            background: "#fff",
            backgroundHover: "#f5f5f5",
            backgroundPress: "#e0e0e0",
            backgroundFocus: "#e0e0e0",
            color: "#11181C",
            colorHover: "#000",
            colorPress: "#000",
            colorFocus: "#000",
            borderColor: "#e0e0e0",
            borderColorHover: "#bdbdbd",
            borderColorPress: "#9e9e9e",
            borderColorFocus: "#9e9e9e",
        },
        dark: {
            background: "#151718",
            backgroundHover: "#1f1f1f",
            backgroundPress: "#2a2a2a",
            backgroundFocus: "#2a2a2a",
            color: "#ECEDEE",
            colorHover: "#fff",
            colorPress: "#fff",
            colorFocus: "#fff",
            borderColor: "#2a2a2a",
            borderColorHover: "#3a3a3a",
            borderColorPress: "#4a4a4a",
            borderColorFocus: "#4a4a4a",
        },
    },
    tokens: {
        size: {
            0: 0,
            1: 4,
            2: 8,
            3: 12,
            4: 16,
            5: 20,
            6: 24,
            7: 28,
            8: 32,
            9: 36,
            10: 40,
            11: 44,
            12: 48,
        },
        space: {
            0: 0,
            1: 4,
            2: 8,
            3: 12,
            4: 16,
            5: 20,
            6: 24,
            7: 28,
            8: 32,
            9: 36,
            10: 40,
            11: 44,
            12: 48,
        },
        radius: {
            0: 0,
            1: 4,
            2: 8,
            3: 12,
            4: 16,
        },
        zIndex: {
            0: 0,
            1: 1,
            2: 2,
            3: 3,
            4: 4,
            5: 5,
        },
    },
    media: {
        xs: { maxWidth: 660 },
        sm: { maxWidth: 800 },
        md: { maxWidth: 1020 },
        lg: { maxWidth: 1280 },
        xl: { maxWidth: 1420 },
        xxl: { maxWidth: 1600 },
        gtXs: { minWidth: 660 + 1 },
        gtSm: { minWidth: 800 + 1 },
        gtMd: { minWidth: 1020 + 1 },
        gtLg: { minWidth: 1280 + 1 },
        short: { maxHeight: 820 },
        tall: { minHeight: 820 },
        hoverNone: { hover: "none" },
        pointerCoarse: { pointer: "coarse" },
    },
    shorthands: {
        px: "paddingHorizontal",
        py: "paddingVertical",
        mx: "marginHorizontal",
        my: "marginVertical",
        bg: "backgroundColor",
        br: "borderRadius",
    },
});

export default config;
